"""empty message

Revision ID: 69ba5887d049
Revises: 597e1eceff78
Create Date: 2020-06-05 14:26:51.311977

"""

# revision identifiers, used by Alembic.
revision = '69ba5887d049'
down_revision = '597e1eceff78'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image')
    # ### end Alembic commands ###
