"""empty message

Revision ID: 762f7313d0f0
Revises: e7f231c9e87f
Create Date: 2020-05-29 11:20:10.311132

"""

# revision identifiers, used by Alembic.
revision = '762f7313d0f0'
down_revision = 'e7f231c9e87f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('author', 'password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=60),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('author', 'password',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
    # ### end Alembic commands ###
